name: Automerge Staging -> Develop

on:
  push:
    branches: [ "staging" ] # triggered when a push to 'staging' happens.
  workflow_dispatch: # on button click

jobs:
  merge-main-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "GitHub Actions # ${GITHUB_ACTOR}"
      - name: Merge 'staging' to 'develop'
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/staging -m "Automerge 'staging' to 'develop'. Action triggered by: ${GITHUB_ACTOR}."
          git push
