name: Automerge Main -> Staging -> Develop

on:
  push:
    branches: [ "main" ] # triggered when a push to 'main' happens.
  workflow_dispatch: # on button click

jobs:
  merge-main-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "GitHub Actions # ${GITHUB_ACTOR}"
      - name: Merge 'main' to 'staging'
        id: Merge
        continue-on-error: true
        run: |
          git fetch --unshallow
          git checkout staging
          git pull
          git merge --no-ff origin/main -m "Automerge 'main' to 'staging'. Action triggered by: ${GITHUB_ACTOR}."
          git push
      - name: Echo Merge Status
        run: echo "Merge was a ${{steps.Merge.outcome}}."
      - name: Create PR on merge failure
        if: steps.Merge.outcome == 'failure'
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automerge Failure
          body: Failed to merge 'main' into 'staging'.
          branch: main
          base: staging


  merge-staging-to-develop:
    needs: merge-main-to-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "GitHub Actions # ${GITHUB_ACTOR}"
      - name: Merge 'staging' to 'develop'
        id: Merge
        continue-on-error: true
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff origin/staging -m "Automerge 'staging' to 'develop'. Action triggered by: ${GITHUB_ACTOR}."
          git push
      - name: Echo Merge Status
        run: echo "Merge was a ${{steps.Merge.outcome}}."
      - name: Create PR on merge failure
        if: steps.Merge.outcome == 'failure'
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automerge Failure
          body: Failed to merge 'staging' into 'develop'.
          branch: staging
          base: develop